### ISSUE TITLE
FadeIn/FadeOut effects should share a filter name.

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/obs-powershell#119]
Right now, one can FadeIn and FadeOut, and then have an effectively invisible source, because there are two opacity filters active.

While this can be somewhat addressed with .Reverse, these two effects should share the same filter name, so that missteps are less likely.

**Comment by I-Am-Jakoby** [comment]
Thank you will be addressed

**Comment by StartAutomating** [comment]
Thanks @I-Am-Jakoby , assigning it to you.
