### ISSUE TITLE
get Get-OBSStats command shows error

### ISSUE THREAD

**Issue by tauseedzaman** [StartAutomating/obs-powershell#162]
i just installd this package according to the docs

when i executed this command

```
Get-OBSStats
```

i got this error

![image](https://github.com/StartAutomating/obs-powershell/assets/64689921/52081a3f-6bf8-4ea5-b0c5-52b70925d103)

**Comment by StartAutomating** [comment]
@tauseedzaman  It seems like you connected to OBS and got disconnected (hence the error)

How you got disconnected is a good question.

This will happen "naturally" if you close /reopen obs (and can be fixed be reimporting or reconnecting)

There are some high volume requests and bad request forms that can cause the websocket to crash.   If you `Receive-Job` the obs connection, you should see the last error that caused it to barf.

Hope this helps, and let me know if it was something I can fix.
